services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "0.0.0.0:16686:16686"
      - "0.0.0.0:4317:4317"
      - "0.0.0.0:4318:4318"
