services:
  postgres:
    container_name: postgres
    image: postgres:17.4-alpine
    restart: always
    volumes:
      - ~/docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

networks:
  casdoor:
    external: true
